name: Test SSH to EC2

on:
  workflow_dispatch: # Manual trigger

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and run a test command
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Connected to EC2 successfully!"
            uname -a
            whoami
