name: Deploy to EC2

on:
  push:
    branches:
      - main   # change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /root/myapp || git clone https://github.com/YOUR_USERNAME/YOUR_REPO.git myapp
            cd myapp
            git pull origin main
            npm install --production   # adjust (mvn package, yarn build, docker, etc.)
            pm2 restart app || pm2 start npm --name "app" -- start
          EOF
