name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

     - name: Test SSH
  run: |
    ssh -i ec2-key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo Connected!"
            cd /home/ubuntu/myapp || git clone https://github.com/YOUR_USERNAME/YOUR_REPO.git myapp
            cd myapp
            git pull origin main
            npm install --production   # adjust for your stack
            pm2 restart app || pm2 start npm --name "app" -- start
          EOF
